### ISSUE TITLE
Saying the word "one" kicks one out of the form

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CognitoFormsDev#116]
![Alexa Developer Console 🔊 2019-04-09 17-14-18](https://user-images.githubusercontent.com/228704/55835891-f7568380-5aea-11e9-876b-4b43a70be6ff.jpg)

Same thing happens if I say "five"

**Comment by tjcocklin** [comment]
The problem here is the input doesn't match any of the Intent handlers, which causes the skill to exit.

Normally the FallbackIntent is suppose to catch, and reply to any input that is not recognized by the handlers according to the docs.

That said, there are many unresolved issues surrounding the use of the FallbackIntent.

 see: https://forums.developer.amazon.com/topics/fallbackintent.html
